import { environment } from '../../../environments/environment';

function createUrl(actionName: string): string {
  return `${environment.apiUrl}${actionName}`;
}

export const appApiResources = {

  login: createUrl('student/login'),
  logout : createUrl('student/logOut'),
  sendOTP: createUrl('student/sendOTP'),
  verifyOTP: createUrl('student/verifyOTP'),
  register: createUrl('student/signup'),
  addInstitute: createUrl('student/institute'),
  setDefaultInstitute: createUrl('student/setDefaultInstitute'),
  setBranch: createUrl('student/setBranch'),

  forGotPassword: createUrl('student/forGotPassword'),
  changePassword: createUrl('student/updatePassword'),
  profilePasswordChange: createUrl('student/changePassword'),
  
  instituteList: createUrl('student/instituteList'),
  dashboard: createUrl('student/dashboard'),
  topic: createUrl('student/getTopicList'),
  content: createUrl('student/getContentList'),
  contentDetails: createUrl('student/getContentFileList'),
  testQuestion: createUrl('student/test'),
  practiceQuestion: createUrl('student/practice'),
  polls: createUrl('student/poll'),
  testResult: createUrl('student/testResult'),
  changeProfilePic: createUrl('student/picture'),
  profileInfo : createUrl('student/student'),
  aboutUs : createUrl('student/aboutUs'),
  privacyPolicies : createUrl('student/privacyPolicies'),
  review : createUrl('student/review'),
  feedBack : createUrl('student/feedBack'),
  testList : createUrl('student/test'),
  education : createUrl('education'),
  countryCityList : createUrl('countryCityList'),
  purchase : createUrl('student/purchase'),
  checkCoupon : createUrl('student/checkCoupon'),
  forumDashboard : createUrl('student/forumDashboard'),
  forumSubject : createUrl('student/forumSubject'),
  forumTopic : createUrl('student/forumTopic'),
  forumArticles : createUrl('student/forumArticles'),
  forumArticle: createUrl('student/forumArticle'),
  discussionForum : createUrl('student/forumDiscussion'),
  discussionForumReply : createUrl('student/forumDiscussionReply'),
  supportRequest : createUrl('student/supportRequest'),
  stctTypesList : createUrl('student/STCTtypesList'),
  supportRequestChat : createUrl('student/supportRequestChat'),
  liveClass : createUrl('student/liveClass'),
  videoLog : createUrl('student/video-log'),
  pdfLog : createUrl('student/pdf-log'),
  audiLog : createUrl('student/audio-log'),
  news : createUrl('student/news'),
  newsCategory : createUrl('student/newsCategory'),
  bundle : createUrl('student/bundle'),
  bundleSet : createUrl('student/bundleSet'),
  bundleSeries : createUrl('student/bundleSeries'),
  bundleQuestion : createUrl('student/bundleQuestion'),
  bundleResult : createUrl('student/bundleResult'),
  reviewCourse : createUrl('student/reviewCourse'),
  notification : createUrl('student/notification'),
  liveClassSignature : createUrl('liveClassSignature'),
  tutor : createUrl('student/tutor'),
  zoomKey : createUrl('student/zoomKey'),
  supportRequestChatRead : createUrl('student/supportRequestChatRead'),
  stripePurchase : createUrl('student/stripePurchase'),
  verifyEmail : createUrl('student/verify'),
};